spring:
  application:
    name: HelloClient

server:
  port: 7211

eureka:
  password: password
  client:
    serviceUrl:
      defaultZone: http://user:${eureka.password}@localhost:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}

endpoints:
  restart:
    enabled: true

resilience4j.circuitbreaker:
  backends:
    default:
      ringBufferSizeInClosedState: 10
      ringBufferSizeInHalfOpenState: 5
      waitInterval: 5000
      failureRateThreshold: 20
      eventConsumerBufferSize: 10

